### ISSUE TITLE
Returns 0 when command fails

### ISSUE THREAD

**Issue by exchgr** [solanolabs/tddium#82]
In POSIX-like operating systems, only successful commands should return 0, while failed commands should return with an exit status of something other than 0. When I run a command that's guaranteed to fail, like `tddium stop` without a build number, `tddium` still returns 0, although the command has failed.

**Comment by Holmes19** [comment]
Hi there,

Good catch, thanks for reaching out about this! I'll make a note of this myself in a separate tracking system, and in the meantime I recommend you file a PR about this issue as well.

-Nick

**Comment by exchgr** [comment]
Should I actually open this on http://github.com/solanolabs/solano?

**Comment by wkj** [comment]
Yes; please do. The ``tddium`` gem is deprecated and will be removed (the ``solano`` gem implements a ``tddium`` command for backwards compatibility.
